#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
# shellcheck source=/dev/null
. "$(readlink -f "$__dirname/../shared.sh")"


# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$2"
fi

CAMELNAME="$(echo "$PROJECTNAME" | to_camel_case)"

# create base project
ew project-base "$PROJECTNAME" "$DESCRIPTION"
cd "$PROJECTNAME" || exit 1

readf 'index.js' \
  | replace 'CAMELNAME' "$CAMELNAME" \
  > index.js

readf 'package.json' \
  | replace 'PROJECTNAME' "$PROJECTNAME" \
  | replace 'DESCRIPTION' "$DESCRIPTION" \
  > package.json

mkdir -p scripts
copy 'scripts/test' 'scripts/test'

# install
npm install -D \
  standard \
  dependency-check
