#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
. "$(readlink -f "$__dirname/../shared.sh")"

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$2"
fi

# define USERNAME
if [ -z "$3" ]; then
  printf 'Under what user on GitHub will this project live?\n❯ '
  read -r USERNAME
  if [ "$USERNAME" = "" ]; then
    printf 'no username provided, exiting\n'
    exit 1
  fi
else
  USERNAME="$3"
fi

CAMELNAME="$(echo "$PROJECTNAME" | to_camel_case)"

# create base project
ew project-base "$PROJECTNAME" "$DESCRIPTION"
cd "$PROJECTNAME" || exit 1

readf "$__dirname/index.js" \
  | replace 'CAMELNAME' "$CAMELNAME" \
  > index.js

readf "$__dirname/package.json" \
  | replace 'PROJECTNAME' "$PROJECTNAME" \
  | replace 'DESCRIPTION' "$DESCRIPTION" \
  | replace 'USERNAME' "$USERNAME" \
  > package.json

# install
npm install -D \
  tape \
  standard \
  dependency-check
