#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cp --preserve=mode "$tmpfile" "$outfile"
}

# define NAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r NAME
  if [ "$NAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  NAME="$1"
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$2"
fi

# create base project
ew project-base "$NAME" "$DESCRIPTION"
cd "$NAME" || exit 1

readf 'index.js' \
  | replace 'DESCRIPTION' "$DESCRIPTION" \
  > index.js

readf 'package.json' \
  | replace 'NAME' "$NAME" \
  | replace 'DESCRIPTION' "$DESCRIPTION" \
  > package.json

mkdir -p scripts
copy 'scripts/test' 'scripts/test'

# install
yarn add --dev \
  standard \
  standard-markdown \
  dependency-check

yarn install
