#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cp --preserve=mode "$tmpfile" "$outfile"
}

ew project-node "$1" "$2"
cd "$1" || exit 1

# dirs
mkdir -p assets/
mkdir -p elements/
mkdir -p lib/
mkdir -p models/
mkdir -p pages/
mkdir -p scripts/

# install
yarn add \
  choo@4 \
  choo-log \
  choo-persist \
  bulk-require \
  tachyons

yarn add --dev \
  bankai \
  bulkify

copy "index.js" "index.js"

git add -A
git commit -m .
