#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

project-base "$1"
cd "$1" || exit 1
npm init -y

# dirs
mkdir -p assets/
mkdir -p elements/
mkdir -p lib/
mkdir -p models/
mkdir -p pages/
mkdir -p scripts/

# install
npm i -S \
  choo \
  choo-log \
  choo-persist \
  bulk-require \
  tachyons

npm i -D \
  bankai \
  bulkify

infile="index.js"
outfile="index.js"
tmpfile="$(readlink -f "$dirname/$infile")"
cat "$tmpfile" > "$outfile"
