#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cat "$tmpfile" > "$outfile"
}

if [ $# = "0" ]; then
  printf 'usage: ew docker <dirname>\n'
  exit 1
fi

printf 'What does this Dockerfile do?\n❯ '
read -r desc
if [ "$desc" = "" ]; then
  printf 'no description provided, exiting\n'
  exit 1
fi

mkdir -p "$1"
cd "$1" || exit 1

readf 'README.md' \
  | replace 'PROJECTNAME' "$1" \
  | replace 'DESCRIPTION' "$desc" \
  > README.md

copy 'Dockerfile' 'Dockerfile'
