[package]
name = "{{PROJECTNAME}}"
version = "1.0.0"
license = "Apache-2.0"
repository = "https://github.com/{{USERNAME}}/{{PROJECTNAME}}"
documentation = "https://docs.rs/{{PROJECTNAME}}"
description = "{{DESCRIPTION}}"
authors = ["{{USERNAME}} <{{EMAIL}}>"]

[dependencies]
