#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cat "$tmpfile" > "$outfile"
}

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

install_dep () {
  printf 'cargo: installing %s\n' "$1"
  cargo add "$1"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

config="$(readlink -f "$dirname/../config.json")"
if [ ! -f "$config" ]; then
  printf 'error: config.json file not found\n'
  exit 1
fi

if [ $# = "0" ]; then
  printf 'usage: ew rust <NAME>\n'
  exit 1
fi

username="$(jq -r '.username' < "$config")"
email="$(jq -r '.email' < "$config")"
NAME="$1"

# create base project
ew project-base "$NAME"
cd "$NAME" || exit 1

# create dirs
mkdir -p 'src/'

# create files
readf Cargo.toml \
  | replace PROJECTNAME "$NAME" \
  | replace USERNAME "$username" \
  | replace EMAIL "$email" \
  > "Cargo.toml"

copy "main.rs" "src/main.rs"
copy "errors.rs" "src/errors.rs"

# install stuff
install_dep clippy
install_dep error-chain
