#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

install_dep () {
  printf 'cargo: installing %s\n' "$1"
  cargo add "$1"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

config="$(readlink -f "$dirname/../config.json")"
if [ ! -f "$config" ]; then
  printf 'error: config.json file not found\n'
  exit 1
fi

if [ $# = "0" ]; then
  printf 'usage: ew rust <projectname>\n'
  exit 1
fi

username="$(jq -r '.username' < "$config")"
email="$(jq -r '.email' < "$config")"
projectname="$1"

# create base project
project-base "$projectname"
cd "$projectname" || exit 1

# create dirs
mkdir -p 'src/'

# create files
infile="Cargo.toml"
outfile="Cargo.toml"
tmpfile="$(readlink -f "$dirname/$infile")"
  replace PROJECTNAME "$projectname" < "$tmpfile" \
  | replace USERNAME "$username" \
  | replace EMAIL "$email" \
  > "$outfile"

infile="main.rs"
outfile="src/main.rs"
tmpfile="$(readlink -f "$dirname/$infile")"
"$outfile" < "$tmpfile"

infile="errors.rs"
outfile="src/errors.rs"
tmpfile="$(readlink -f "$dirname/$infile")"
"$outfile" < "$tmpfile"

# install stuff
install_dep clippy
install_dep error-chain
