#!/bin/sh

tmpdir="asdf"

# run
ew rust "$tmpdir"
cd "$tmpdir" || exit 1

# inspect
tree
print () {
  for f in *; do
    if [ -f "$f" ]; then
      cat "$f";
    elif [ -d "$f" ]; then
      cd "$f" || exit 1
      print
      cd ../ || exit 1
    fi
  done
}
print

# cleanup
cd ../ || exit 1
rm -rf "$tmpdir"
