#!/bin/sh

initialize -h > /dev/null
if [ $? -ne 0 ]; then
  npm i -g initialize
fi

if [ ! -z "$1" ]; then
  name="$1"
  shift
  initialize "$@"
  cd "$name" || exit 1
else
  initialize "$@"
  cd "$name" || exit 1
fi
