#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
source "$(readlink -f "$__dirname/../shared.sh")"

mkdir -p ".github/"
copy "$__dirname/CODE_OF_CONDUCT.md" ".github/CODE_OF_CONDUCT.md"
copy "$__dirname/CONTRIBUTING.md" ".github/CONTRIBUTING.md"
copy "$__dirname/CERTIFICATE.md" "CERTIFICATE"
copy "$__dirname/ISSUE_TEMPLATE.md" ".github/ISSUE_TEMPLATE.md"
copy "$__dirname/PULL_REQUEST_TEMPLATE.md" ".github/PULL_REQUEST_TEMPLATE.md"
copy "$__dirname/stale.yml" ".github/stale.yml"
