#!/bin/sh

if [ $# = "0" ]; then
  printf 'usage: ew playground <projectname>\n'
  exit 1
fi

name="playground-$1"
project-base "$name"

readme="$(pwd)/$name/README.md"
gsed -i '3 i ## See also\n' "$readme"
