#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
. "$(readlink -f "$__dirname/../shared.sh")"

# create base project
ew project-node "$@"
cd "$PROJECTNAME" || exit 1

readf "$__dirname/index.js" \
  > index.js

touch app.js

# install
npm install -S \
  bankai \
  choo \
  choo-log \
  electron \
  electron-default-window \
  merry \
  sheetify \
  tachyons

npm install -D electron-builder
