#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
# shellcheck source=/dev/null
. "$(readlink -f "$__dirname/../shared.sh")"

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$2"
fi

mkdir -p "$PROJECTNAME"
cd "$PROJECTNAME" || exit 1

readf "$__dirname/README.md" \
  | replace PROJECTNAME "$PROJECTNAME" \
  | replace DESCRIPTION "$DESCRIPTION" \
  > README.md

copy "$__dirname/_gitignore" ".gitignore"
copy "$__dirname/LICENSE" "LICENSE"

git init
