#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cat "$tmpfile" > "$outfile"
}

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$2"
fi

mkdir -p "$PROJECTNAME"
cd "$PROJECTNAME" || exit 1

readf "README.md" \
  | replace PROJECTNAME "$PROJECTNAME" \
  | replace DESCRIPTION "$DESCRIPTION" \
  > README.md

copy "_gitignore" ".gitignore"
copy "LICENSE" "LICENSE"

git init
