#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")

readf () {
  file="$(readlink -f "$dirname/$1")"
  cat "$file"
}

replace () {
  sed "s/{{$1}}/$2/g"
}

copy () {
  infile="$1"
  outfile="$2"
  tmpfile="$(readlink -f "$dirname/$infile")"
  cat "$tmpfile" > "$outfile"
}

if [ $# = "0" ]; then
  printf 'usage: project-base <projectname>\n'
  exit 1
fi

projectname="$1"
mkdir -p "$projectname"
cd "$projectname" || exit 1

readf "README.md" \
  | replace projectname "$projectname" \
  > README.md

copy "_gitignore" ".gitignore"
copy "LICENSE" "LICENSE"
