#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
source "$(readlink -f "$__dirname/../shared.sh")"

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

ew rust "$@"

pushd "$PROJECTNAME"

readf "$__dirname/main.rs" \
  | replace PROJECTNAME "$(echo "$PROJECTNAME" | tr '-' '_')" \
  > src/main.rs

copy "$__dirname/cli.rs" src/cli.rs
copy "$__dirname/lib.rs" src/lib.rs
copy "$__dirname/build.rs" build.rs

cargo add human-panic
cargo add structopt
cargo add log
cargo add clap_flags

cargo add -B structopt
cargo add -B clap_flags
cargo add -B failure
popd
