#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
source "$(readlink -f "$__dirname/../shared.sh")"

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
fi

ew rust "$@"

pushd "$PROJECTNAME"
rm src/lib.rs

readf "$__dirname/main.rs" \
  | replace PROJECTNAME "$(echo "$PROJECTNAME" | tr '-' '_')" \
  > src/main.rs

copy "$__dirname/main.rs" src/main.rs
copy "$__dirname/cli.rs" src/cli.rs
copy "$__dirname/build.rs" src/build.rs
cargo add structopt
popd
