#!/bin/sh

__dirname=$(dirname "$(readlink -f "$0")")
source "$(readlink -f "$__dirname/../shared.sh")"

# define PROJECTNAME
if [ -z "$1" ]; then
  printf 'What is the name of the project?\n❯ '
  read -r PROJECTNAME
  if [ "$PROJECTNAME" = "" ]; then
    printf 'no name provided, exiting\n'
    exit 1
  fi
else
  PROJECTNAME="$1"
  shift
fi

# define DESCRIPTION
if [ -z "$2" ]; then
  printf 'What does this project do?\n❯ '
  read -r DESCRIPTION
  if [ "$DESCRIPTION" = "" ]; then
    printf 'no description provided, exiting\n'
    exit 1
  fi
else
  DESCRIPTION="$(echo "$2" | sed 's|\.$||')."
  shift
fi

ew rust "$PROJECTNAME" "$DESCRIPTION" "$@"

pushd "$PROJECTNAME"
rm src/lib.rs

readf "$__dirname/main.rs" \
  | replace PROJECTNAME "$(echo "$PROJECTNAME" | tr '-' '_')" \
  > src/main.rs

readf "$__dirname/cli.rs" \
  | replace DESCRIPTION "$DESCRIPTION" \
  > src/cli.rs

copy "$__dirname/lib.rs" src/lib.rs
copy "$__dirname/build.rs" build.rs

cargo add exitfailure
cargo add human-panic
cargo add structopt
cargo add log
cargo add clap_flags

cargo add -B mkdirp
cargo add -B structopt
cargo add -B clap_flags
cargo add -B failure
popd
